### ISSUE TITLE
Update for "nullSafeGet"

### ISSUE THREAD

**Issue by divlv** [vojtechruz/jsonb-hibernate-example#2]
Hi, Vojtech!

I have changed your "nullSafeGet" method a little bit.

```java
public Object nullSafeGet(ResultSet rs, String[] names, SessionImplementor session, Object owner) throws HibernateException, SQLException {
        PGobject o = (PGobject) rs.getObject(names[0]);
        if (o.getValue() != null) {
            return gson.fromJson(o.getValue(), Map.class);
        }
        return new HashMap<String, String>();
}
```

At the following place:
```java
        PGobject o = (PGobject) rs.getObject(names[0]);
        if (o.getValue() != null) {
```
the object "o" can be _null_ itself. So the _o.getValue()_ will throw an NPE. (this was happen to me ;-) )
My version looks like this:
```java
if (o != null && o.getValue() != null) { ...
```

BTW, thank you for such great code sample! 
I was unable to find anything simpler and clearer.

**Comment by vojtechruz** [comment]
Thank you very much for the report. I am glad that you find the example useful. I have updated the code as you suggested.
